name: CI - Frontend Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências
        working-directory: frontend
        run: npm install

      - name: Rodar testes com Vitest
        working-directory: frontend
        run: |
          npx vitest run --environment jsdom
